### ISSUE TITLE
Reconsider design of the popup

### ISSUE THREAD

**Issue by denar90** [denar90/sloth#7]
I'm not a fan of the current design of popup, is anyone has ideas - they are more that welcome :)

Current design
![image](https://user-images.githubusercontent.com/6231516/53666483-e0fd1280-3c76-11e9-9850-7c0ad9dec0e1.png)

**Comment by hibuno** [comment]
Hi @denar90,

Just an idea from me, we can use single `select` to define a url for throttling.

Maybe like this :

```html
<select>
  <option value="all">All tabs</option>
  <option value="https://github.com/">https://github.com</option>
  ...
</select>
```

And the design will be like image below.

![sloth](https://user-images.githubusercontent.com/17744043/53712259-b37fb700-3e78-11e9-82e2-f5414f0ec8a9.jpg)

Thank you

**Comment by denar90** [comment]
Hi @muhibbudins, it looks lovely :heart_eyes: 
Where do you think we can place checkboxes on a popup?

**Comment by hibuno** [comment]
Hi @denar90, What checkboxes? All tabs? As i explain above, i think we can use single `<select>` with options to set current origin or set to origin on all tabs 😄

**Comment by denar90** [comment]
Yeah, I got it :) but probably we will have one more checkbox after merging #5. Also If we wanna get rid of checkbox for `Apply to current tab (URL origin)` then probably we should consider having this message as notification for user that all related origin tabs also will be throttled.

**Comment by hibuno** [comment]
Oh i see, i missed to see the PR. Maybe we can add a `cog` icon at top left popup, to set an option `auto-reload` or another options in the future.

For message `Apply to current tab (URL origin)` we can place it below a `Apply` button.

**Comment by denar90** [comment]
Sounds awesome!!! Like your way thinking about UI 👍

**Comment by hibuno** [comment]
Sounds good! Thanks for awesome project! 👍

**Comment by denar90** [comment]
Thanks :) Would you like to apply new design? :)

**Comment by denar90** [comment]
@muhibbudins can you share prototype file of your awesome design (sketch, or photoshop, or smth)? So probably me or someone can take it for implementation :)

**Comment by hibuno** [comment]
Hi @denar90,

Sorry for late response, i've created a PR for this issue. So can custom it again on function or other.

Reference #8 

Thank you
